### ISSUE TITLE
Failure importing potholes.json

### ISSUE THREAD

**Issue by simonw** [simonw/git-history#10]
```
% git clone https://github.com/patricktrainer/open-potholes
% cd open-potholes
% git-history file potholes.db potholes.json --id service_request
  [#############-----------------------]  19/50   38%  00:00:04Traceback (most recent call last):
  File "/Users/simon/.local/bin/git-history", line 8, in <module>
    sys.exit(cli())
  File "/Users/simon/.local/pipx/venvs/git-history/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/simon/.local/pipx/venvs/git-history/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/simon/.local/pipx/venvs/git-history/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/simon/.local/pipx/venvs/git-history/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/simon/.local/pipx/venvs/git-history/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/simon/.local/pipx/venvs/git-history/lib/python3.10/site-packages/git_history/cli.py", line 261, in file
    db["items"].insert_all(
  File "/Users/simon/.local/pipx/venvs/git-history/lib/python3.10/site-packages/sqlite_utils/db.py", line 2596, in insert_all
    self.insert_chunk(
  File "/Users/simon/.local/pipx/venvs/git-history/lib/python3.10/site-packages/sqlite_utils/db.py", line 2424, in insert_chunk
    row = list(self.rows_where("rowid = ?", [self.last_rowid]))[0]
IndexError: list index out of range
```
From https://github.com/patricktrainer/open-potholes

**Comment by simonw** [comment]
Running that command multiple times eventually processes the whole file, presumably missing some data.

**Comment by simonw** [comment]
It's because that JSON has a `rowid` column:
```
    "rowid": "841311"
```
Adding `rowid` as a reserved column may fix this.
